--- #YAML:1.0
name:                Math-BigApprox
version:             0.001001
abstract:            Fast and small way to closely approximate very large values.
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Tye McQueen
distribution_type:   module
requires:     
    POSIX:                         0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
